# Generated by Django 4.1.3 on 2022-11-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='substance',
            old_name='PubChem_alias',
            new_name='PubChem_Alias',
        ),
        migrations.AddField(
            model_name='substance',
            name='Local_Image',
            field=models.ImageField(default='./default_image.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='substance',
            name='PubChem_Formula',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='substance',
            name='PubChem_Mass',
            field=models.FloatField(),
        ),
    ]
