# Generated by Django 4.1.2 on 2022-10-27 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("length", models.IntegerField()),
                ("height", models.IntegerField()),
                ("width", models.IntegerField()),
            ],
        ),
    ]
